name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.13'
    - name: Install dependencies
      run: npm run build:dev:ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: tests/playwright-report/
        retention-days: 30
